#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Motor,  port5,            ,             tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  port10,            ,             tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

motor[port5] = 0;

untilTouch(dgtl1);
motor[port5] = 127;
wait1Msec(2000);
motor[port5] = 0;

}
